# Criar usuário POST http://localhost:3003/user/signup Content-Type: application/json

{
"name": "Giulia Verruck",
"email": "giulia@gmail.com", "password": "123456789",
"role": "admin"

}

### # Fazer login # @name login POST http://localhost:3003/login Content-Type: application/json

{
"email": "nathalia@gmail.com",
"password": "123456789"
}

### @token = {{login.response.body.token}} # Pegar o própio perfil GET http://localhost:3003/user/profile Authorization: {{token}}

###

# Pegar o perfil de outro usuário pelo id GET http://localhost:3003/user-by-id/ea5d65fb-d156-4a76-b636-0662876c4813 Authorization: {{token}}

###

# Criar recita POST http://localhost:3003/recipe/create Content-Type: application/json Authorization: {{token}}

{
"title": "Bolo de de Chocolate", "description": "Molhadinho, com muita cobertura"
}

###

# Pegar receita GET http://localhost:3003/recipe-by-id/9cd4645b-1a1c-4f77-994f-266e1de9e1a5 Authorization: {{token}}

###

# Seguir usuário POST http://localhost:3003/user/follow Content-Type: application/json Authorization: {{token}}

{
"idSeguindo": "ffb639bb-eb7d-460f-9aaf-ed9ba2f8dfae"
}

###

# Deixar de seguir usuário POST http://localhost:3003/user/unfollow Content-Type: application/json Authorization: {{token}}

{
"userToUnfollowId": "e4b69625-b729-4fb9-b024-8bc7002986a2"
}

### # Pegar feed de receitas das pessoas seguidas pelo id logado GET http://localhost:3003/user/feed Authorization: {{token}}

###

# Editar receita Put http://localhost:3003/edit/recipe/9cd4645b-1a1c-4f77-994f-266e1de9e1a5 Content-Type: application/json Authorization: {{token}}

{
"title": "Cocada de doce de leite", "description": "Vai coco e leite"
}

###

# Deletar receita DELETE http://localhost:3003/delete/recipe/152cda4c-d704-4073-ba5f-7d41ee31f0f4 Content-Type: application/json Authorization: {{token}}

###

# Deletar a conta do usuário DELETE http://localhost:3003/delete/account/845dfdf9-6a18-439d-aea2-75b4e3e8a289 Content-Type: application/json Authorization: {{token}}